package com.example.kornel.alphaui.weather;

public class WeatherConsts {
    public static final String[] CONDITION_LIST_ENG = new String[]{
            "tornado",
            "tropical storm",
            "hurricane",
            "severe thunderstorms",
            "thunderstorms",
            "mixed rain and snow",
            "mixed rain and sleet",
            "mixed snow and sleet",
            "freezing drizzle",
            "drizzle",
            "freezing rain",
            "showers",
            "showers",
            "snow flurries",
            "light snow showers",
            "blowing snow",
            "snow",
            "hail",
            "sleet",
            "dust",
            "foggy",
            "haze",
            "smoky",
            "blustery",
            "windy",
            "cold",
            "cloudy",
            "mostly cloudy (night)",
            "mostly cloudy (day)",
            "partly cloudy (night)",
            "partly cloudy (day)",
            "clear (night)",
            "sunny",
            "fair (night)",
            "fair (day)",
            "mixed rain and hail",
            "hot",
            "isolated thunderstorms",
            "scattered thunderstorms",
            "scattered thunderstorms",
            "scattered showers",
            "heavy snow",
            "scattered snow showers",
            "heavy snow",
            "partly cloudy",
            "thundershowers",
            "snow showers",
            "isolated thundershowers",
            "not available",
    };

    public static final String[] CONDITION_LIST_PL = new String[]{
            "Tornado",
            "Burza tropikalna",
            "Huragan",
            "Silne burze",
            "Burze z piorunami",
            "Deszcz i śnieg",
            "Deszcz ze śniegiem",
            "Deszcz ze śniegiem",
            "Marznąca mżawka",
            "Mżawka",
            "Marznący deszcz",
            "Deszcz",
            "Deszcz",
            "Podmuchy śniegu",
            "Lekkie opady śniegu",
            "Opady śniegu",
            "Śnieg",
            "Grad",
            "Śnieg z deszczem",
            "Kurz",
            "Mglisty",
            "Mgła",
            "Dymny",
            "Przenikliwy",
            "Wietrzny",
            "Zimno",
            "Pochmurny",
            "Przeważnie pochmurno",
            "Pochmurno",
            "Częściowe zachmurzenie",
            "Częściowe zachmurzenie",
            "Czyste niebo",
            "Słonecznie",
            "Pogodnie",
            "Pogodnie",
            "Mieszany deszcz i grad",
            "Upał",
            "Pojedyncze burze",
            "Przelotne burze",
            "Przelotne burze",
            "Przelotne opady",
            "Duże opady śniegu",
            "Rozległe opady śnieżne",
            "Duże opady śniegu",
            "Częściowe zachmurzenie",
            "Ulewny deszcz",
            "Opady śniegu",
            "Pojedyncze burze",
            "Niedostępne"
    };

    public static String getConditionEngByCode(int code) {
        return CONDITION_LIST_ENG[code];
    }

    public static String getConditionPlByCode(int code) {
        return CONDITION_LIST_PL[code];
    }
}